name: Build and upload artifacts

on:
  workflow_call:
    secrets:
      BUILD_COMMAND:
        required: true
      LANGUAGE:
        required: true
      ARTIFACT_ARCHIVE_DIR:
        required: true
      ARTIFACT_ARCHIVE_BASE_NAME:
        required: true


jobs:
  build-and-upload-artifacts:
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    env:
      BUILD_COMMAND: ${{ secrets.BUILD_COMMAND }}
      LANGUAGE: ${{ secrets.LANGUAGE }}
      ARTIFACT_ARCHIVE_DIR: ${{ secrets.ARTIFACT_ARCHIVE_DIR }}
      ARTIFACT_ARCHIVE_BASE_NAME: ${{ secrets.ARTIFACT_ARCHIVE_BASE_NAME }}
    name: Build and upload artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/setup-java@v2
        if: env.LANGUAGE == 'java'
        with:
          distribution: adopt
          java-version: '11'
      - name: Cache (Java)
        if: env.LANGUAGE == 'java'
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-node@v2
        if: env.LANGUAGE == 'nodejs'
        with:
          node-version: '14'
      - name: Cache (NodeJS)
        if: env.LANGUAGE == 'nodejs'
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-python@v2
        if: env.LANGUAGE == 'python'
        with:
          python-version: '3.8'
      - name: Cache (Python)
        if: env.LANGUAGE == 'python'
        uses: actions/cache@v2
        with:
          path: |
           ~/go/pkg/mod
           ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build artifacts - ${{ matrix.architecture }}
        run: GOARCH=${{ matrix.architecture }} ${{ env.BUILD_COMMAND }}
        working-directory: ${{ env.LANGUAGE }}
      - name: Upload artifacts - ${{ env.LANGUAGE }}
        if: env.LANGUAGE == 'python' && success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ env.LANGUAGE }}-${{ matrix.architecture }}-artifacts
          path: ${{ env.LANGUAGE }}/${{ env.ARTIFACT_ARCHIVE_DIR }}/${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ matrix.architecture }}.zip
          if-no-files-found: error
      - name: Upload artifacts - ${{ env.LANGUAGE }}
        if: env.LANGUAGE == 'nodejs' && success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ env.LANGUAGE }}-${{ matrix.architecture }}-artifacts
          path: ${{ env.LANGUAGE }}/${{ env.ARTIFACT_ARCHIVE_DIR }}/${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ matrix.architecture }}.zip
          if-no-files-found: error
      - name: Upload artifacts - ${{ env.LANGUAGE }}
        if: env.LANGUAGE == 'java' && success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ env.LANGUAGE }}-${{ matrix.architecture }}-artifacts
          path: ${{ env.LANGUAGE }}/${{ env.ARTIFACT_ARCHIVE_DIR }}/${{ env.ARTIFACT_ARCHIVE_BASE_NAME }}-${{ matrix.architecture }}.zip
          if-no-files-found: error
