name: Main Build - NodeJS

on:
  push:
    branches:
      - main
    paths:
      - 'nodejs/**'

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: nodejs
      ARTIFACT_ARCHIVE: packages/layer/build/opentelemetry-nodejs.zip

  create-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE: opentelemetry-nodejs.zip
      PUBLISH: "false"
      LANGUAGE: nodejs
      LAYER_NAME: main
