name: Pull Request Build - Python

on:
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: python
      ARTIFACT_ARCHIVE: src/build/opentelemetry-python.zip

  create-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE: opentelemetry-python.zip
      PUBLISH: "false"
      LANGUAGE: python
      LAYER_NAME: main
