name: Pull Request Build - Java

on:
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/*-java.yml'

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: java
      ARTIFACT_ARCHIVE_DIR: layer-wrapper/build/distributions
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-java-wrapper

  create-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-java-wrapper
      PUBLISH: "false"
      LANGUAGE: java
      LAYER_NAME: ${GITHUB_HEAD_REF}
