name: Pull Request Build - Python

on:
  pull_request:
    paths:
      - 'python/**'

jobs:
  build-python-artifacts:
    runs-on: ubuntu-20.04
    env:
      BUILD_COMMAND: ./build.sh
      PUBLISH_COMMAND: ./publish.sh
      LANGUAGE: python
      LAYER_ARCHIVE: src/build/opentelemetry-python.zip
    name: Build artifacts
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        aws_region: [ eu-central-1 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache (Python)
        uses: actions/cache@v2
        with:
          path: |
           ~/go/pkg/mod
           ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build layer - ${{ matrix.architecture }}
        run: GOARCH=${{ matrix.architecture }} ${{ env.BUILD_COMMAND }}
        working-directory: ${{ env.LANGUAGE }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ matrix.aws_region }}
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Create Lambda Layer - ${{ matrix.architecture }}
        run: ${{ env.PUBLISH_COMMAND }} ${{ matrix.architecture }} "${GITHUB_HEAD_REF}-${{ env.LANGUAGE }}-${{ matrix.architecture }}" "${GITHUB_HEAD_REF}-${{ env.LANGUAGE }}-${{ matrix.architecture }}" ${{ env.LAYER_ARCHIVE }} layer-${{ matrix.architecture }}.zip "false"
        working-directory: ${{ env.LANGUAGE }}
      - name: Clean s3
        if: always()
        run: |
          aws s3 rb --force s3://${GITHUB_HEAD_REF}-${{ env.LANGUAGE }}-${{ matrix.architecture }}
