name: Pull Request Build - nodejs

on:
  pull_request:
    paths:
        - 'nodejs/**'

jobs:
  build-nodejs-artifacts:
    runs-on: ubuntu-20.04
    env:
      BUILD_COMMAND: ./build.sh
      PUBLISH_COMMAND: ./publish.sh
      LANGUAGE: nodejs
      LAYER_ARCHIVE: packages/layer/build/opentelemetry-nodejs.zip
    name: Build artifacts
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        aws_region: [ eu-central-1 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache (NodeJS)
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache (Python)
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build layer - ${{ matrix.architecture }}
        run: GOARCH=${{ matrix.architecture }} ${{ env.BUILD_COMMAND }}
        working-directory: ${{ env.LANGUAGE }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ matrix.aws_region }}
      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
      - name: Create Lambda Layer - ${{ matrix.architecture }}
        run: ${{ env.PUBLISH_COMMAND }} ${{ matrix.architecture }} "" "test-ll-${{ matrix.architecture }}" ${{ env.LAYER_ARCHIVE }} layer-${{ matrix.architecture }}.zip
        working-directory: ${{ env.LANGUAGE }}
      - name: clean s3
        if: always()
        run: |
          aws s3 rb --force s3://test-ll-${{ matrix.architecture }}
