name: Test Pull Request Build - Python

on:
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/*-python.yml'

env:
  BUILD_COMMAND: ./build.sh
  PUBLISH_COMMAND: ./publish.sh
  LANGUAGE: python
  ARTIFACT_LOCATION: src/build/opentelemetry-python.zip
  PUBLISH: false

jobs:
  build-artifacts:
    uses: Sumologic/opentelemetry-lambda/.github/workflows/build-artifacts.yml@main
    secrets:
      BUILD_COMMAND: ${{ env.BUILD_COMMAND }}
      LANGUAGE: ${{ env.LANGUAGE }}
      ARTIFACT_ARCHIVE: ${{ env.ARTIFACT_LOCATION }}

  create-lambda-layer:
    needs: build-artifacts
    uses: Sumologic/opentelemetry-lambda/.github/workflows/build-artifacts.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ${{ env.PUBLISH_COMMAND }}
      ARTIFACT_ARCHIVE: ${{ env.ARTIFACT_LOCATION }}
      PUBLISH: ${{ env.PUBLISH }}
      LANGUAGE: ${{ env.LANGUAGE }}

