name: Build and upload artifacts

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PUBLISH_COMMAND:
        required: true
      ARTIFACT_ARCHIVE:
        required: true
      PUBLISH:
        required: true
      LANGUAGE:
        required: true


jobs:
  create-lambda-layer-artifacts:
    name: Build and upload artifacts
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        aws_region: [ eu-central-1, eu-west-1 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ secrets.LANGUAGE }}-${{ matrix.architecture }}-artifacts
          path: ~/artifact
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ matrix.aws_region }}
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Create Lambda Layer - ${{ matrix.architecture }}
        run: ${{ secrets.PUBLISH_COMMAND }} ${{ matrix.architecture }} "${GITHUB_HEAD_REF}-${{ secrets.LANGUAGE }}-${{ matrix.architecture }}" "${GITHUB_HEAD_REF}-${{ secrets.LANGUAGE }}-${{ matrix.architecture }}-${{ matrix.aws_region }}" ~/artifact/${{ secrets.ARTIFACT_ARCHIVE }} layer-${{ matrix.architecture }}.zip ${{ secrets.PUBLISH }} ${{ matrix.aws_region }}
        working-directory: ${{ secrets.LANGUAGE }}
      - name: Clean s3
        if: always()
        run: |
          aws s3 rb --force s3://${GITHUB_HEAD_REF}-${{ secrets.LANGUAGE }}-${{ matrix.architecture }}-${{ matrix.aws_region }} --region ${{ matrix.aws_region }}
