name: Release Build - NodeJS

on:
  push:
    tags:
      - 'nodejs-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: nodejs
      ARTIFACT_ARCHIVE_DIR: packages/layer/build
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-nodejs

  create-release-lambda-layer:
    needs: build-release-artifacts
    uses: ./.github/workflows/publish-release-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.OSC_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OSC_AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-nodejs
      PUBLISH: "true"
      LANGUAGE: nodejs
      LAYER_NAME: ${GITHUB_HEAD_REF}

  create-release:
    needs: create-release-lambda-layer
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/java-v})"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true

          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true

          body: |
            ## Sumo Logic OTel NodeJS AWS Lambda Layer version: ${{ steps.extract_tag.outputs.tag }}
            ### Changelog
            **TODO**
            ### AWS Lambda Layers:
            **TODO**
          artifacts: "artifacts/*"
          artifactErrorsFailBuild: true
          replacesArtifacts: true