name: Release Build - Java

on:
  push:
    tags:
      - 'java-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-java-artifacts:
    runs-on: ubuntu-20.04
    env:
      BUILD_COMMAND: ./build.sh
      PUBLISH_COMMAND: ./publish.sh
      LANGUAGE: java
      LAYER_ARCHIVE: layer-wrapper/build/distributions/opentelemetry-java-wrapper.zip
    name: Build artifacts
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        aws_region: [ us-east-1, us-east-2, us-west-1, us-west-2, af-south-1, ap-east-1, ap-south-1, ap-northeast-3,
                      ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-northeast-1, ca-central-1, eu-central-1,
                      eu-west-1, eu-west-2, eu-south-1, eu-west-3, eu-north-1, me-south-1, sa-east-1 ]
        exclude:
          - aws_region: ap-northeast-2
            architecture: arm64
          - aws_region: af-south-1
            architecture: arm64
          - aws_region: ca-central-1
            architecture: arm64
          - aws_region: eu-north-1
            architecture: arm64
          - aws_region: eu-west-3
            architecture: arm64
          - aws_region: sa-east-1
            architecture: arm64
          - aws_region: us-west-1
            architecture: arm64
          - aws_region: ap-east-1
            architecture: arm64
          - aws_region: eu-south-1
            architecture: arm64
          - aws_region: me-south-1
            architecture: arm64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Cache (Java)
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache (Python)
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build layer - ${{ matrix.architecture }}
        run: GOARCH=${{ matrix.architecture }} ${{ env.BUILD_COMMAND }}
        working-directory: ${{ env.LANGUAGE }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.OSC_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.OSC_AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ matrix.aws_region }}
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Create Lambda Layer - ${{ matrix.architecture }}
        run: ${{ env.PUBLISH_COMMAND }} ${{ matrix.architecture }} "" "${GITHUB_HEAD_REF}-${{ env.LANGUAGE }}-${{ matrix.architecture }}-release" ${{ env.LAYER_ARCHIVE }} layer-${{ matrix.architecture }}.zip "true"
        working-directory: ${{ env.LANGUAGE }}
      - name: Clean s3
        if: always()
        run: |
          aws s3 rb --force s3://${GITHUB_HEAD_REF}-${{ env.LANGUAGE }}-${{ matrix.architecture }}-release
