name: Release Build - Python

on:
  push:
    tags:
      - 'python-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: python
      ARTIFACT_ARCHIVE: packages/layer/build/opentelemetry-nodejs.zip

  create-release-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-release-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.OSC_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OSC_AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE: opentelemetry-python.zip
      PUBLISH: "true"
      LANGUAGE: python
      LAYER_NAME: ${GITHUB_HEAD_REF}
