name: Release Build - Java

on:
  push:
    tags:
      - 'java-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets:
      BUILD_COMMAND: ./build.sh
      LANGUAGE: java
      ARTIFACT_ARCHIVE: layer-wrapper/build/distributions/opentelemetry-java-wrapper.zip

  create-release-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-release-lambda-layer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.OSC_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OSC_AWS_SECRET_ACCESS_KEY }}
      PUBLISH_COMMAND: ./publish.sh
      ARTIFACT_ARCHIVE: opentelemetry-java-wrapper.zip
      PUBLISH: "true"
      LANGUAGE: java
      LAYER_NAME: ${GITHUB_HEAD_REF}
